# Generated by Django 5.2.5 on 2025-09-15 06:57

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelmasterapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JigUnload_TrayId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tray_id', models.CharField(help_text='Tray ID', max_length=100)),
                ('tray_qty', models.IntegerField(help_text='Quantity in the tray')),
                ('lot_id', models.CharField(help_text='Lot ID', max_length=100)),
                ('draft_save', models.BooleanField(default=False)),
                ('top_tray', models.BooleanField(default=False)),
                ('delink_tray', models.BooleanField(default=False, help_text='Is tray delinked')),
                ('rejected_tray', models.BooleanField(default=False, help_text='Is tray rejected')),
            ],
        ),
        migrations.CreateModel(
            name='JigUnloadDraft',
            fields=[
                ('draft_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_lot_id', models.CharField(max_length=50)),
                ('model_number', models.CharField(max_length=100)),
                ('total_quantity', models.IntegerField()),
                ('draft_data', models.JSONField()),
                ('combined_lot_ids', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jig_unload_draft',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JigUnloadAfterTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jig_qr_id', models.CharField(help_text='Jig QR ID', max_length=100)),
                ('combine_lot_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=list, help_text='List of combined lot IDs', size=None)),
                ('lot_id', models.CharField(editable=False, help_text='Auto-generated unique lot ID', max_length=50, unique=True)),
                ('unload_lot_id', models.CharField(blank=True, editable=False, help_text='Auto-generated unload lot ID (format: JUL{YYYYMMDD}{sequence})', max_length=50, null=True, unique=True)),
                ('total_case_qty', models.IntegerField(help_text='Total case quantity')),
                ('plating_stk_no', models.CharField(blank=True, help_text='Plating Stock Number (auto-populated from combined lots)', max_length=100, null=True)),
                ('polish_stk_no', models.CharField(blank=True, help_text='Polish Stock Number (auto-populated from combined lots)', max_length=100, null=True)),
                ('plating_stk_no_list', models.JSONField(blank=True, default=list, null=True)),
                ('polish_stk_no_list', models.JSONField(blank=True, default=list, null=True)),
                ('version_list', models.JSONField(blank=True, default=list, null=True)),
                ('category', models.CharField(blank=True, help_text='Category (auto-populated from combined lots)', max_length=100, null=True)),
                ('tray_type', models.CharField(blank=True, help_text='Tray Type (auto-populated from combined lots)', max_length=100, null=True)),
                ('tray_capacity', models.IntegerField(blank=True, help_text='Tray Capacity (auto-populated from combined lots)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unload_accepted', models.BooleanField(default=False, help_text='Indicates if the unload was accepted')),
                ('accepted_qty', models.IntegerField(default=0, help_text='Accepted quantity during unload')),
                ('unload_audit_accepted', models.BooleanField(default=False, help_text='Indicates if the unload was accepted')),
                ('audit_accepted_qty', models.IntegerField(default=0, help_text='Accepted quantity during unload')),
                ('last_process_module', models.CharField(blank=True, help_text='Last Process Module', max_length=255, null=True)),
                ('next_process_module', models.CharField(blank=True, help_text='Next Process Module', max_length=255, null=True)),
                ('rejected_nickle_ip_stock', models.BooleanField(default=False, help_text='Rejected Nickle IP Stock')),
                ('nq_qc_accepted_qty', models.IntegerField(default=0, help_text='Nq QC Accepted Quantity')),
                ('rejected_audit_nickle_ip_stock', models.BooleanField(default=False, help_text='Rejected Nickle Audit Stock')),
                ('audit_check', models.BooleanField(default=False, help_text='Audit Check')),
                ('nq_holding_reason', models.CharField(blank=True, help_text='Brass Reason for holding the batch', max_length=255, null=True)),
                ('nq_release_reason', models.CharField(blank=True, help_text='Brass Reason for releasing the batch', max_length=255, null=True)),
                ('nq_hold_lot', models.BooleanField(default=False, help_text='Indicates if the lot is on hold n Brass')),
                ('nq_release_lot', models.BooleanField(default=False)),
                ('nq_pick_remarks', models.CharField(blank=True, help_text='JIG Pick Remarks', max_length=100, null=True)),
                ('nq_missing_qty', models.IntegerField(default=0, help_text='Missing quantity in IQF')),
                ('nq_physical_qty', models.IntegerField(default=0, help_text='Original physical quantity in IQF')),
                ('nq_qc_accptance', models.BooleanField(default=False)),
                ('nq_qc_few_cases_accptance', models.BooleanField(default=False)),
                ('nq_qc_rejection', models.BooleanField(default=False)),
                ('nq_rejection_tray_scan_status', models.BooleanField(default=False)),
                ('nq_accepted_tray_scan_status', models.BooleanField(default=False)),
                ('nq_onhold_picking', models.BooleanField(default=False, help_text='Nickle QC On Hold Picking')),
                ('nq_draft', models.BooleanField(default=False, help_text='Nickle QC Draft Save')),
                ('nq_qc_accepted_qty_verified', models.BooleanField(default=False, help_text='Nickle QC Accepted Quantity Verified')),
                ('nq_last_process_date_time', models.DateTimeField(blank=True, help_text='Last Process Date Time', null=True)),
                ('na_holding_reason', models.CharField(blank=True, help_text='Brass Reason for holding the batch', max_length=255, null=True)),
                ('na_release_reason', models.CharField(blank=True, help_text='Brass Reason for releasing the batch', max_length=255, null=True)),
                ('na_hold_lot', models.BooleanField(default=False, help_text='Indicates if the lot is on hold n Brass')),
                ('na_release_lot', models.BooleanField(default=False)),
                ('na_pick_remarks', models.CharField(blank=True, help_text='JIG Pick Remarks', max_length=100, null=True)),
                ('na_missing_qty', models.IntegerField(default=0, help_text='Missing quantity in IQF')),
                ('na_physical_qty', models.IntegerField(default=0, help_text='Original physical quantity in IQF')),
                ('na_qc_accptance', models.BooleanField(default=False)),
                ('na_qc_few_cases_accptance', models.BooleanField(default=False)),
                ('na_qc_rejection', models.BooleanField(default=False)),
                ('na_rejection_tray_scan_status', models.BooleanField(default=False)),
                ('na_accepted_tray_scan_status', models.BooleanField(default=False)),
                ('na_onhold_picking', models.BooleanField(default=False, help_text='Nickle QC On Hold Picking')),
                ('na_draft', models.BooleanField(default=False, help_text='Nickle QC Draft Save')),
                ('na_ac_accepted_qty_verified', models.BooleanField(default=False, help_text='Nickle QC Accepted Quantity Verified')),
                ('na_last_process_date_time', models.DateTimeField(blank=True, help_text='Last Process Date Time', null=True)),
                ('na_qc_accepted_qty', models.IntegerField(default=0, help_text='NA QC Accepted Quantity')),
                ('spider_holding_reason', models.CharField(blank=True, help_text='Spider Reason for holding the batch', max_length=255, null=True)),
                ('spider_release_reason', models.CharField(blank=True, help_text='Spider Reason for releasing the batch', max_length=255, null=True)),
                ('spider_hold_lot', models.BooleanField(default=False, help_text='Indicates if the lot is on hold n Spider')),
                ('spider_release_lot', models.BooleanField(default=False)),
                ('spider_pick_remarks', models.CharField(blank=True, help_text='Spider Pick Remarks', max_length=100, null=True)),
                ('send_to_nickel_brass', models.BooleanField(default=False, help_text='Send to Nickel Brass')),
                ('missing_qty', models.IntegerField(default=0)),
                ('Un_loaded_date_time', models.DateTimeField(blank=True, help_text='Un Loaded Date Time', null=True)),
                ('jig_physical_qty', models.IntegerField(default=0, help_text='Original physical quantity in IQF')),
                ('location', models.ManyToManyField(blank=True, help_text='Locations (auto-populated from combined lots)', to='modelmasterapp.location')),
                ('plating_color', models.ForeignKey(blank=True, help_text='Plating Color (auto-populated from combined lots)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelmasterapp.plating_color')),
                ('polish_finish', models.ForeignKey(blank=True, help_text='Polish Finish (auto-populated from combined lots)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelmasterapp.polishfinishtype')),
                ('selected_user', models.ForeignKey(blank=True, help_text='User who created the lot', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='Version (auto-populated from combined lots)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modelmasterapp.version')),
            ],
            options={
                'verbose_name': 'Jig Unload After Table',
                'verbose_name_plural': 'Jig Unload After Tables',
            },
        ),
    ]
