# Generated by Django 5.2.6 on 2025-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Unloading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigunloadaftertable',
            name='unload_missing_qty',
            field=models.IntegerField(default=0, help_text='Missing quantity in Jig Unloading'),
        ),
    ]
