# Generated by Django 5.2.6 on 2025-10-08 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Unloading', '0002_jigunloadaftertable_unload_missing_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JigUnloadAutoSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('main_lot_id', models.CharField(db_index=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('total_quantity', models.IntegerField(default=0)),
                ('tray_data', models.JSONField(default=list)),
                ('combined_lot_ids', models.JSONField(default=list)),
                ('tray_type_capacity', models.CharField(default='Normal - 16', max_length=50)),
                ('missing_qty', models.IntegerField(default=0)),
                ('jig_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jig_unload_autosave',
                'indexes': [models.Index(fields=['user', 'main_lot_id', 'updated_at'], name='jig_unload__user_id_6c4d51_idx'), models.Index(fields=['session_key', 'main_lot_id', 'updated_at'], name='jig_unload__session_8a2b13_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'main_lot_id'), name='unique_user_unload_autosave'), models.UniqueConstraint(condition=models.Q(('session_key__isnull', False)), fields=('session_key', 'main_lot_id'), name='unique_session_unload_autosave')],
            },
        ),
    ]
