# Generated by Django 5.2.5 on 2025-09-15 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IQF', '0001_initial'),
        ('modelmasterapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='iqftrayid',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelmasterapp.modelmastercreation'),
        ),
        migrations.AddField(
            model_name='iqftrayid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='iqf_draft_store',
            unique_together={('lot_id', 'draft_type')},
        ),
        migrations.AlterUniqueTogether(
            name='iqf_optimaldistribution_draft',
            unique_together={('lot_id', 'user')},
        ),
    ]
