# Generated by Django 5.2.6 on 2026-01-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IQF', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqf_rejected_trayscan',
            name='top_tray',
            field=models.BooleanField(default=False, help_text='Is this the top tray in rejection'),
        ),
    ]
