# Generated by Django 5.2.6 on 2026-02-19 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IQF', '0003_iqf_rejected_trayscan_top_tray'),
    ]

    operations = [
        migrations.AddField(
            model_name='iqftrayid',
            name='remaining_qty',
            field=models.IntegerField(default=0, help_text='Remaining quantity in tray after rejection distribution'),
        ),
    ]
