# Generated by Django 5.2.5 on 2025-09-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0002_rowaccesslock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmaster',
            name='ep_bath_type',
            field=models.CharField(choices=[('Bright', 'Bright'), ('Semi Bright', 'Semi Bright'), ('Dull', 'Dull')], help_text='Type of bath this number belongs to', max_length=20),
        ),
    ]
