# Generated by Django 5.2.6 on 2025-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0007_modelmaster_polishing_stk_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmaster',
            name='model_no',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmaster',
            name='plating_stk_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelmaster',
            name='polishing_stk_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='Category of the model', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='plating_color',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='plating_stk_no',
            field=models.CharField(blank=True, db_index=True, help_text='Plating Stock Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='polish_finish',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='polishing_stk_no',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='vendor_internal',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plating_color',
            name='plating_color_internal',
            field=models.CharField(db_index=True, help_text='Short internal code used in stock number (e.g., B for Black)', max_length=10),
        ),
    ]
