# Generated by Django 5.2.6 on 2026-01-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0010_alter_totalstockmodel_parent_lot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalstockmodel',
            name='parent_lot_id',
        ),
    ]
