# Generated by Django 5.2.5 on 2026-01-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0002_remove_jigdetails_bath_numbers_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE \"Jig_Loading_jigcompleted\" ALTER COLUMN hold_status TYPE varchar(20);",
            reverse_sql="ALTER TABLE \"Jig_Loading_jigcompleted\" ALTER COLUMN hold_status TYPE boolean USING (hold_status::boolean);"
        ),
    ]
