# Generated by Django 5.2.5 on 2026-01-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0003_add_hold_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigcompleted',
            name='is_multi_model',
            field=models.BooleanField(default=False),
        ),
    ]
