# Generated by Django 5.2.5 on 2026-01-17 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0004_add_missing_fields'),
    ]

    operations = [
    ]
