# Generated by Django 5.2.5 on 2026-01-17 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0005_merge_20260117_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigcompleted',
            name='IP_loaded_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jigcompleted',
            name='bath_numbers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jig_Loading.bathnumbers'),
        ),
        migrations.AddField(
            model_name='jigcompleted',
            name='jig_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jigcompleted',
            name='last_process_module',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jigcompleted',
            name='pick_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jigcompleted',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
