# Generated by Django 5.2.5 on 2026-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0006_rename_jig_loading__user_ba_ba9b8_idx_jig_loading_user_id_77a274_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigcompleted',
            name='no_of_model_cases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
