# Generated by Django 5.2.5 on 2026-01-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0007_rename_jig_loading__user_ba_ba9b8_idx_jig_loading_user_id_77a274_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='jigautosave',
            new_name='Jig_Loading_user_id_77a274_idx',
            old_name='Jig_Loading__user_ba_ba9b8_idx',
        ),
        migrations.AddField(
            model_name='jigcompleted',
            name='new_lot_ids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jigcompleted',
            name='plating_stk_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
