# Generated by Django 5.2.5 on 2026-01-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0008_rename_jig_loading__user_ba_ba9b8_idx_jig_loading_user_id_77a274_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigcompleted',
            name='plating_stock_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jigloadingmanualdraft',
            name='plating_stock_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
