# Generated by Django 5.2.5 on 2026-01-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0009_auto_20260119_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigcompleted',
            name='new_lot_ids',
        ),
        migrations.RemoveField(
            model_name='jigcompleted',
            name='plating_stk_no',
        ),
        migrations.AlterField(
            model_name='jigcompleted',
            name='draft_status',
            field=models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('partial', 'Partial')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='jigloadingmanualdraft',
            name='draft_status',
            field=models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted'), ('partial', 'Partial')], default='active', max_length=20),
        ),
    ]
