# Generated by Django 5.2.5 on 2026-01-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0010_remove_jigcompleted_new_lot_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigcompleted',
            name='partial_lot_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jigcompleted',
            name='draft_status',
            field=models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='jigloadingmanualdraft',
            name='draft_status',
            field=models.CharField(choices=[('active', 'Active'), ('submitted', 'Submitted')], default='active', max_length=20),
        ),
    ]
