# Generated by Django 5.2.5 on 2026-01-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0011_jigcompleted_partial_lot_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jigcompleted',
            name='partial_lot_qty',
        ),
        migrations.AddField(
            model_name='jigcompleted',
            name='partial_lot_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
