# Generated by Django 5.2.5 on 2026-01-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0012_remove_jigcompleted_partial_lot_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jigcompleted',
            name='partial_lot_id',
            field=models.CharField(blank=True, help_text='New lot ID for remaining cases in partial submission', max_length=100, null=True),
        ),
    ]
