# Generated by Django 5.2.5 on 2025-09-15 06:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Recovery_DP', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryIP_Rejection_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason_id', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('rejection_reason', models.TextField(help_text='Reason for rejection')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryIP_RejectionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryIP_Accepted_TrayID_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='RLot ID', max_length=50, null=True)),
                ('top_tray_id', models.CharField(max_length=100)),
                ('top_tray_qty', models.IntegerField(blank=True, help_text='Quantity in the tray', null=True)),
                ('is_draft', models.BooleanField(default=False, help_text='Draft Save')),
                ('is_save', models.BooleanField(default=False, help_text='Save')),
                ('delink_trays', models.JSONField(blank=True, default=list, help_text='Multiple Delink Trays')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryIP_Accepted_TrayScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='RLot ID', max_length=50, null=True)),
                ('accepted_tray_quantity', models.CharField(help_text='Accepted Tray Quantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryIP_Rejection_ReasonStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='RLot ID', max_length=50, null=True)),
                ('total_rejection_quantity', models.PositiveIntegerField(help_text='Total Rejection Quantity')),
                ('batch_rejection', models.BooleanField(default=False)),
                ('lot_rejected_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rejection_reason', models.ManyToManyField(blank=True, to='Recovery_IS.recoveryip_rejection_table')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryIP_Rejected_TrayScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='RLot ID', max_length=50, null=True)),
                ('rejected_tray_quantity', models.CharField(help_text='Rejected Tray Quantity')),
                ('rejected_tray_id', models.CharField(blank=True, help_text='Rejected Tray ID', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rejection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recovery_IS.recoveryip_rejection_table')),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryIPTrayId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='RLot ID', max_length=50, null=True)),
                ('tray_id', models.CharField(help_text='Tray ID', max_length=100)),
                ('tray_quantity', models.IntegerField(blank=True, help_text='Quantity in the tray', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('top_tray', models.BooleanField(default=False)),
                ('delink_tray', models.BooleanField(default=False, help_text='Is tray delinked')),
                ('delink_tray_qty', models.CharField(blank=True, help_text='Delinked quantity', max_length=50, null=True)),
                ('IP_tray_verified', models.BooleanField(default=False, help_text='Is tray verified in RecoveryIP')),
                ('rejected_tray', models.BooleanField(default=False, help_text='Is tray rejected')),
                ('new_tray', models.BooleanField(default=True, help_text='Is tray new')),
                ('tray_type', models.CharField(blank=True, help_text='Type of tray (Jumbo, Normal, etc.) - filled by admin', max_length=50, null=True)),
                ('tray_capacity', models.IntegerField(blank=True, help_text='Capacity of this specific tray - filled by admin', null=True)),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Recovery_DP.recoverymastercreation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RecoveryIP Tray ID',
                'verbose_name_plural': 'RecoveryIP Tray IDs',
            },
        ),
        migrations.CreateModel(
            name='RecoveryIP_Rejection_Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(help_text='RLot ID', max_length=50, unique=True)),
                ('draft_data', models.JSONField(help_text='JSON data containing rejection details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_rejection_remarks', models.CharField(blank=True, help_text='RLot rejection remarks for batch rejection', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lot_id', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RecoveryIP_TrayVerificationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=100)),
                ('tray_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_status', models.CharField(blank=True, choices=[('pass', 'Pass'), ('fail', 'Fail')], max_length=10, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lot_id', 'tray_id')},
            },
        ),
    ]
