# Generated by Django 5.2.5 on 2025-09-15 06:57

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brass_QC_Rejection_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rejection_reason_id', models.CharField(blank=True, editable=False, max_length=10, null=True)),
                ('rejection_reason', models.TextField(help_text='Reason for rejection')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the record')),
            ],
        ),
        migrations.CreateModel(
            name='BrassTrayId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='Lot ID', max_length=50, null=True)),
                ('tray_id', models.CharField(help_text='Tray ID', max_length=100)),
                ('tray_quantity', models.IntegerField(blank=True, help_text='Quantity in the tray', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('top_tray', models.BooleanField(default=False)),
                ('delink_tray', models.BooleanField(default=False, help_text='Is tray delinked')),
                ('delink_tray_qty', models.CharField(blank=True, help_text='Delinked quantity', max_length=50, null=True)),
                ('IP_tray_verified', models.BooleanField(default=False, help_text='Is tray verified in IP')),
                ('rejected_tray', models.BooleanField(default=False, help_text='Is tray rejected')),
                ('new_tray', models.BooleanField(default=True, help_text='Is tray new')),
                ('tray_type', models.CharField(blank=True, help_text='Type of tray (Jumbo, Normal, etc.) - filled by admin', max_length=50, null=True)),
                ('tray_capacity', models.IntegerField(blank=True, help_text='Capacity of this specific tray - filled by admin', null=True)),
            ],
            options={
                'verbose_name': 'Brass Tray ID',
                'verbose_name_plural': 'Brass Tray IDs',
            },
        ),
        migrations.CreateModel(
            name='Brass_Qc_Accepted_TrayID_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='Lot ID', max_length=50, null=True)),
                ('tray_id', models.CharField(max_length=100, unique=True)),
                ('tray_qty', models.IntegerField(blank=True, help_text='Quantity in the tray', null=True)),
                ('is_draft', models.BooleanField(default=False, help_text='Draft Save')),
                ('is_save', models.BooleanField(default=False, help_text='Save')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brass_Qc_Accepted_TrayScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='Lot ID', max_length=50, null=True)),
                ('accepted_tray_quantity', models.CharField(help_text='Accepted Tray Quantity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brass_QC_Draft_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=255)),
                ('batch_id', models.CharField(max_length=255)),
                ('draft_type', models.CharField(max_length=50)),
                ('draft_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Brass_QC_Rejection_ReasonStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='Lot ID', max_length=50, null=True)),
                ('total_rejection_quantity', models.PositiveIntegerField(help_text='Total Rejection Quantity')),
                ('batch_rejection', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the record')),
                ('lot_rejected_comment', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rejection_reason', models.ManyToManyField(blank=True, to='Brass_QC.brass_qc_rejection_table')),
            ],
        ),
        migrations.CreateModel(
            name='Brass_QC_Rejected_TrayScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='Lot ID', max_length=50, null=True)),
                ('rejected_tray_quantity', models.CharField(help_text='Rejected Tray Quantity')),
                ('rejected_tray_id', models.CharField(blank=True, help_text='Rejected Tray ID', max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rejection_reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Brass_QC.brass_qc_rejection_table')),
            ],
        ),
        migrations.CreateModel(
            name='Brass_TopTray_Draft_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(max_length=255)),
                ('batch_id', models.CharField(max_length=255)),
                ('tray_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tray_qty', models.IntegerField(blank=True, null=True)),
                ('delink_trays_data', models.JSONField(blank=True, default=dict)),
                ('delink_tray_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
