# Generated by Django 5.2.6 on 2026-02-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InputScreening', '0003_alter_ip_rejected_trayscan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip_rejected_trayscan',
            name='user',
        ),
    ]
