# Generated by Django 5.2.6 on 2025-10-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0004_ssoaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalstockmodel',
            name='brass_lot_rejection_proceeded',
            field=models.BooleanField(default=False, help_text='Brass lot rejection proceed clicked'),
        ),
    ]
