# Generated by Django 5.2.5 on 2025-11-19 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0005_totalstockmodel_brass_lot_rejection_proceeded'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalstockmodel',
            name='jig_draft',
            field=models.BooleanField(default=False, help_text='Jig Loading Draft Save'),
        ),
    ]
