# Generated by Django 5.2.5 on 2025-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0006_totalstockmodel_jig_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelmaster',
            name='polishing_stk_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
