# Generated by Django 5.2.5 on 2026-01-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0008_alter_modelmaster_model_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalstockmodel',
            name='parent_lot_id',
            field=models.CharField(blank=True, help_text='Parent Lot ID for split lots', max_length=50, null=True),
        ),
    ]
