# Generated by Django 5.2.5 on 2026-01-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0009_totalstockmodel_parent_lot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalstockmodel',
            name='parent_lot_id',
            field=models.CharField(blank=True, help_text='Parent Lot ID for partial lots', max_length=50, null=True),
        ),
    ]
