# Generated by Django 5.2.5 on 2026-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0011_remove_totalstockmodel_parent_lot_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelmaster',
            name='polishing_stk_no',
        ),
        migrations.RemoveField(
            model_name='totalstockmodel',
            name='brass_lot_rejection_proceeded',
        ),
        migrations.RemoveField(
            model_name='totalstockmodel',
            name='jig_draft',
        ),
        migrations.AlterField(
            model_name='modelmaster',
            name='ep_bath_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmaster',
            name='model_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmaster',
            name='plating_stk_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='category',
            field=models.CharField(blank=True, help_text='Category of the model', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='plating_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='plating_stk_no',
            field=models.CharField(blank=True, help_text='Plating Stock Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='polish_finish',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='polishing_stk_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='modelmastercreation',
            name='vendor_internal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='plating_color',
            name='plating_color_internal',
            field=models.CharField(help_text='Short internal code used in stock number (e.g., B for Black)', max_length=10),
        ),
        migrations.DeleteModel(
            name='SSOAccount',
        ),
    ]
