# Generated by Django 5.2.5 on 2026-01-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelmasterapp', '0012_remove_modelmaster_polishing_stk_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalstockmodel',
            name='jig_draft',
            field=models.BooleanField(default=False, help_text='Jig Draft Save'),
        ),
    ]
