# Generated by Django 5.2.6 on 2025-11-19 08:27

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        
        ('modelmasterapp', '0006_totalstockmodel_jig_draft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider_TrayId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_id', models.CharField(blank=True, help_text='Lot ID', max_length=50, null=True)),
                ('tray_id', models.CharField(help_text='Tray ID', max_length=100)),
                ('tray_quantity', models.IntegerField(blank=True, help_text='Quantity in the tray', null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('top_tray', models.BooleanField(default=False)),
                ('delink_tray', models.BooleanField(default=False, help_text='Is tray delinked')),
                ('delink_tray_qty', models.CharField(blank=True, help_text='Delinked quantity', max_length=50, null=True)),
                ('IP_tray_verified', models.BooleanField(default=False, help_text='Is tray verified in IP')),
                ('rejected_tray', models.BooleanField(default=False, help_text='Is tray rejected')),
                ('new_tray', models.BooleanField(default=True, help_text='Is tray new')),
                ('tray_type', models.CharField(blank=True, help_text='Type of tray (Jumbo, Normal, etc.) - filled by admin', max_length=50, null=True)),
                ('tray_capacity', models.IntegerField(blank=True, help_text='Capacity of this specific tray - filled by admin', null=True)),
                ('batch_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelmasterapp.modelmastercreation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Spider Tray ID',
                'verbose_name_plural': 'Spider Tray IDs',
            },
        ),
        migrations.CreateModel(
            name='SpiderJigDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jig_qr_id', models.CharField(max_length=100)),
                ('faulty_slots', models.IntegerField(default=0)),
                ('jig_type', models.CharField(max_length=50)),
                ('jig_capacity', models.IntegerField()),
                ('bath_tub', models.CharField(blank=True, help_text='Bath Tub', max_length=100, null=True)),
                ('plating_color', models.CharField(max_length=50)),
                ('empty_slots', models.IntegerField(default=0)),
                ('ep_bath_type', models.CharField(max_length=50)),
                ('total_cases_loaded', models.IntegerField()),
                ('jig_cases_remaining_count', models.IntegerField(blank=True, default=0, null=True)),
                ('forging', models.CharField(max_length=100)),
                ('no_of_model_cases', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('no_of_cycle', models.IntegerField(default=1)),
                ('lot_id', models.CharField(max_length=100)),
                ('new_lot_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('electroplating_only', models.BooleanField(default=False)),
                ('lot_id_quantities', models.JSONField(blank=True, null=True)),
                ('draft_save', models.BooleanField(default=False, help_text='Draft Save')),
                ('delink_tray_data', models.JSONField(blank=True, default=list, null=True)),
                ('half_filled_tray_data', models.JSONField(blank=True, default=list, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('jig_position', models.CharField(choices=[('Top', 'Top'), ('Middle', 'Middle'), ('Bottom', 'Bottom')], default='Top', help_text='Jig position: Top, Middle, or Bottom', max_length=10)),
                ('remarks', models.CharField(blank=True, help_text='Remarks (max 50 words)', max_length=50)),
                ('pick_remarks', models.CharField(blank=True, help_text='Remarks (max 50 words)', max_length=50)),
                ('jig_unload_draft', models.BooleanField(default=False)),
                ('combined_lot_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('jig_loaded_date_time', models.DateTimeField(blank=True, help_text='Last Process Date/Time', null=True)),
                ('IP_loaded_date_time', models.DateTimeField(blank=True, help_text='Ip last Process Date/Time', null=True)),
                ('last_process_module', models.CharField(blank=True, help_text='Last Process Module', max_length=100)),
                ('unload_over', models.BooleanField(default=False)),
                ('Un_loaded_date_time', models.DateTimeField(blank=True, help_text='Ip last Process Date/Time', null=True)),
                ('bath_numbers', models.ForeignKey(blank=True, help_text='Related Bath Numbers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jig_Loading.bathnumbers')),
            ],
        ),
    ]
