# Generated by Django 5.2.5 on 2026-01-16 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spider_Spindle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderjigdetails',
            name='bath_numbers',
        ),
    ]
