# Generated by Django 5.2.5 on 2026-01-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0001_initial'),
        ('Spider_Spindle', '0002_remove_spiderjigdetails_bath_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderjigdetails',
            name='bath_numbers',
            field=models.ForeignKey(blank=True, help_text='Related Bath Numbers', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Jig_Loading.bathnumbers'),
        ),
    ]
