# Generated by Django 5.2.6 on 2026-01-16 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jigloadtrayid',
            name='broken_hooks_excluded_qty',
            field=models.IntegerField(default=0),
        ),
    ]
