# Generated by Django 5.2.5 on 2025-11-22 18:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jigloadingmanualdraft',
            unique_together={('batch_id', 'lot_id', 'user')},
        ),
    ]
