# Generated by Django 5.2.6 on 2025-11-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jig_Loading', '0002_update_manual_draft_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='jig',
            name='batch_id',
            field=models.CharField(blank=True, help_text='Batch ID for which Jig is locked', max_length=100, null=True),
        ),
    ]
